# These are supported funding model platforms

github: [chcordova] # Mi perfil de GitHub Sponsors
# Example: github: [your-username, another-username]

# Other platforms (uncomment and replace with your usernames/links if you use them)
# patreon: YOUR_PATREON_USERNAME
# open_collective: YOUR_OPENCOLLECTIVE_USERNAME
# ko_fi: YOUR_KOFI_USERNAME
# tidelift: PLATFORM_NAME/PACKAGE_NAME # Example: tidelift: npm/babel
# community_bridge: PROJECT_NAME # Example: community_bridge: cloud-foundry
# liberapay: YOUR_LIBERAPAY_USERNAME
# issuehunt: YOUR_ISSUEHUNT_USERNAME
# custom: ['https://www.your-custom-link.com', 'https://www.another-custom-link.org'] # Replace with up to 4 custom URLs